[target.'cfg(not(target_arch = "wasm32"))']
rustflags = [
    "-C",
    "target-cpu=native",
    "--cfg",
    "aws_sdk_unstable",  # needed for aws-smithy-types + serde-(de)serialize
]


[alias]
test-unit = "nextest run --lib --bins --profile unit"
test-e2e = "nextest run -p tensorzero_internal --test e2e --features e2e_tests"
test-all = "nextest run -p tensorzero_internal --features e2e_tests"
test-batch = "nextest run -p tensorzero_internal --features batch_tests"

run-e2e = "run --bin gateway --features e2e_tests -- tensorzero_internal/tests/e2e/tensorzero.toml"
watch-e2e = "watch -x run-e2e"

[package]
name = "tensorzero_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tensorzero_internal = { path = "../tensorzero_internal" }
axum = { workspace = true }
tracing = { version = "0.1.40", features = ["log", "release_max_level_debug"] }
tracing-subscriber = { version = "0.3.18", features = [
    "env-filter",
    "fmt",
    "json",
] }
tokio = { workspace = true }
mimalloc = "0.1.43"

[lints]
workspace = true
